import { Destination, TourPackage, Paged } from '@/types';
import { Listing, Vehicle, Blog } from './api';

export const SEED_DESTINATIONS: Destination[] = [
  {
    _id: 'seed-dest-1',
    name: 'Srinagar',
    slug: 'srinagar',
    region: 'Jammu & Kashmir',
    country: 'India',
    description: 'The summer capital: Dal Lake, handcrafted wooden houseboats, vibrant floating markets, and historic Mughal gardens.',
    bestTime: 'Apr–Oct',
    startingPrice: 9500,
    rating: 4.8,
    popularity: 98,
    location: { coordinates: [74.7973, 34.0837] },
    images: [{ url: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80' }],
  },
  {
    _id: 'seed-dest-2',
    name: 'Gulmarg',
    slug: 'gulmarg',
    region: 'Jammu & Kashmir',
    country: 'India',
    description: 'The meadow of flowers: home to the world’s highest gondola, powdery ski slopes, and breathtaking views of Apharwat peak.',
    bestTime: 'Dec–Mar (Snow), May–Sep (Meadows)',
    startingPrice: 11000,
    rating: 4.9,
    popularity: 95,
    location: { coordinates: [74.3805, 34.0484] },
    images: [{ url: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=1200&q=80' }],
  },
  {
    _id: 'seed-dest-3',
    name: 'Pahalgam',
    slug: 'pahalgam',
    region: 'Jammu & Kashmir',
    country: 'India',
    description: 'The valley of shepherds: rushing Lidder river, pine-scented breeze, and the cinematic landscapes of Betaab and Aru valleys.',
    bestTime: 'Apr–Oct',
    startingPrice: 10000,
    rating: 4.7,
    popularity: 92,
    location: { coordinates: [75.3150, 34.0161] },
    images: [{ url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80' }],
  },
  {
    _id: 'seed-dest-4',
    name: 'Sonamarg',
    slug: 'sonamarg',
    region: 'Jammu & Kashmir',
    country: 'India',
    description: 'The golden meadow: alpine peaks, perennial Thajiwas glacier, and the scenic mountain gateway to Ladakh along the Sindh river.',
    bestTime: 'May–Sep',
    startingPrice: 10500,
    rating: 4.6,
    popularity: 88,
    location: { coordinates: [75.2930, 34.3020] },
    images: [{ url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80' }],
  },
  {
    _id: 'seed-dest-5',
    name: 'Ladakh',
    slug: 'ladakh',
    region: 'Ladakh',
    country: 'India',
    description: 'High altitude wonderland: dramatic lunar landscapes, crystal azure Pangong Lake, ancient gompas, and world’s highest motorable passes.',
    bestTime: 'May–Sep',
    startingPrice: 22000,
    rating: 4.9,
    popularity: 90,
    location: { coordinates: [77.5771, 34.1526] },
    images: [{ url: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80' }],
  },
  {
    _id: 'seed-dest-6',
    name: 'Manali',
    slug: 'manali',
    region: 'Himachal Pradesh',
    country: 'India',
    description: 'Himalayan sanctuary: snow-capped Rohtang pass, Solang adventure valley, cedar forests, and hot sulfur springs.',
    bestTime: 'Mar–Jun, Dec–Feb',
    startingPrice: 12000,
    rating: 4.6,
    popularity: 85,
    location: { coordinates: [77.1887, 32.2396] },
    images: [{ url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80' }],
  },
];

export const SEED_PACKAGES: TourPackage[] = [
  {
    _id: 'seed-pkg-1',
    title: 'Kashmir Paradise: 7-Day Valley Odyssey',
    slug: 'kashmir-7-days',
    durationDays: 7,
    basePrice: 18500,
    discountPercent: 12,
    images: [{ url: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80' }],
    overview: 'A complete Himalayan escapade through Srinagar, Gulmarg, Pahalgam, and the glacier trails of Sonamarg.',
    highlights: ['Sunset shikara ride on Dal Lake', 'Apharwat peak gondola cable car ride', 'Betaab Valley & Lidder river exploration', 'Luxury heritage houseboat stay with Kashmiri Wazwan dinner'],
    itinerary: [
      { day: 1, title: 'Arrival in Srinagar & Dal Lake Shikara', description: 'Airport pickup, check-in to heritage houseboat, sunset shikara ride.', meals: ['Dinner'] },
      { day: 2, title: 'Mughal Gardens & Old Srinagar Heritage', description: 'Visit Nishat Bagh, Shalimar Bagh, and historic downtown bazaar.', meals: ['Breakfast', 'Dinner'] },
      { day: 3, title: 'Excursion to Gulmarg & Gondola Ride', description: 'Full day in Gulmarg, Phase 1 & 2 gondola, pine forest walk.', meals: ['Breakfast', 'Dinner'] },
      { day: 4, title: 'Gulmarg to Pahalgam Valley of Shepherds', description: 'Drive along saffron fields of Pampore to scenic Pahalgam.', meals: ['Breakfast', 'Dinner'] },
      { day: 5, title: 'Betaab Valley, Aru & Chandanwari', description: 'Explore lush green valleys and pristine alpine streams.', meals: ['Breakfast', 'Dinner'] },
      { day: 6, title: 'Sonamarg Gateway & Thajiwas Glacier', description: 'Day trip to Sonamarg, pony trek to snow glacier.', meals: ['Breakfast', 'Dinner'] },
      { day: 7, title: 'Departure from Srinagar', description: 'Souvenir shopping and transfer to Srinagar Airport.', meals: ['Breakfast'] },
    ],
    included: ['Heritage Houseboat & 4-Star Mountain Resorts', 'Breakfast and gourmet dinners', 'Dedicated sanitized private SUV cab', 'All sightseeing & toll permits'],
    excluded: ['Airfare', 'Personal pony or sledging charges', 'Gondola tickets', 'Travel insurance'],
    pickupLocation: 'Srinagar International Airport',
    transport: 'Private Innova / Crysta SUV',
    cancellationPolicy: 'Free cancellation up to 7 days before departure.',
    maxTravellers: 12,
    rating: 4.9,
    reviewCount: 42,
    destination: { name: 'Srinagar', slug: 'srinagar' },
  },
  {
    _id: 'seed-pkg-2',
    title: 'Gulmarg Winter Wonderland Ski & Snow Tour',
    slug: 'gulmarg-winter-ski',
    durationDays: 5,
    basePrice: 24500,
    discountPercent: 15,
    images: [{ url: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=1200&q=80' }],
    overview: 'Experience the finest dry powder snow in Asia with guided skiing, snowboarding, and luxury cozy chalets.',
    highlights: ['Two-day beginner or advanced ski lessons with certified instructor', 'Phase 2 Gondola ride up to 3,950m', 'Bonfire and traditional saffron Kehwa evenings', 'Heated luxury timber lodge accommodation'],
    included: ['Heated luxury boutique hotel stay', 'Ski gear rental and instructor fees', 'Daily buffet breakfast & hot mountain dinner', 'Private heated transport from Srinagar'],
    excluded: ['Flights', 'Extreme backcountry insurance', 'Lunch'],
    maxTravellers: 8,
    rating: 4.8,
    reviewCount: 29,
    destination: { name: 'Gulmarg', slug: 'gulmarg' },
  },
  {
    _id: 'seed-pkg-3',
    title: 'Pahalgam Pine Valley & River Retreat',
    slug: 'pahalgam-river-retreat',
    durationDays: 4,
    basePrice: 14200,
    discountPercent: 10,
    images: [{ url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80' }],
    overview: 'Unwind along the crystal rushing Lidder River with pine forest walks, trout fishing, and serene mountain vistas.',
    highlights: ['Riverside cottage stay with sound of flowing water', 'Private day trip to Baisaran (Mini Switzerland)', 'Trout angling experience & riverside picnic', 'Chandanwari snow bridge trek'],
    included: ['Riverside cottage accommodation', 'Breakfast and dinner', 'Private cab for all transfers and local sightseeing'],
    excluded: ['Personal horses/ponies', 'Lunch and personal expenses'],
    maxTravellers: 10,
    rating: 4.7,
    reviewCount: 34,
    destination: { name: 'Pahalgam', slug: 'pahalgam' },
  },
  {
    _id: 'seed-pkg-4',
    title: 'Ladakh High Passes & Pangong Expedition',
    slug: 'ladakh-high-passes',
    durationDays: 8,
    basePrice: 29800,
    discountPercent: 10,
    images: [{ url: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80' }],
    overview: 'Traverse the Khardung La pass, camp beside shifting turquoise shades of Pangong Lake, and discover Nubra Valley sand dunes.',
    highlights: ['Khardung La high-altitude crossing at 17,982 ft', 'Double-humped camel safari in Hunder dunes', 'Stargazing campsite at Pangong Tso', 'Monasteries of Thiksey, Hemis and Shey Palace'],
    included: ['Glamping camps & deluxe hotels', 'Oxygen-equipped 4x4 vehicle', 'Inner Line Permits & environmental fees', 'Daily breakfast & dinner'],
    excluded: ['Flight tickets', 'Lunch', 'Personal tips'],
    maxTravellers: 14,
    rating: 4.9,
    reviewCount: 56,
    destination: { name: 'Ladakh', slug: 'ladakh' },
  },
  {
    _id: 'seed-pkg-5',
    title: 'Kashmir Honeymoon Special with Romantic Houseboat',
    slug: 'kashmir-honeymoon-special',
    durationDays: 6,
    basePrice: 26500,
    discountPercent: 18,
    images: [{ url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80' }],
    overview: 'Crafted for romance: candle-lit dinner on Dal Lake, flower-decked room, scenic cable car, and tranquil pine walks.',
    highlights: ['Decorated bridal houseboat suite with lake view', 'Private shikara photoshoot at sunrise', 'Candlelit dinner with traditional Kashmiri Rogan Josh or vegetarian feast', 'Complimentary honeymoon cake & dry fruit basket'],
    included: ['Luxury houseboat & 4-star mountain view resorts', 'Special floral bed decoration & candlelight dinner', 'Private chauffeured sedan', 'All breakfast and dinners'],
    excluded: ['Airfare', 'Shopping and monument entries'],
    maxTravellers: 2,
    rating: 5.0,
    reviewCount: 68,
    destination: { name: 'Srinagar', slug: 'srinagar' },
  },
  {
    _id: 'seed-pkg-6',
    title: 'Sonamarg & Great Himalayan Trek Gateway',
    slug: 'sonamarg-trek-gateway',
    durationDays: 5,
    basePrice: 16800,
    discountPercent: 15,
    images: [{ url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80' }],
    overview: 'For mountain lovers: Thajiwas glacier walks, sparkling alpine streams, camping under starry skies, and trailhead routes.',
    highlights: ['Hike to Thajiwas Glacier with experienced mountain guide', 'Campfire evening along Sindh River', 'Scenic drive through high mountain gorge', 'Visit to Zero Point near Zoji La pass'],
    included: ['Alpine lodge stay & luxury tents', 'Certified mountain guide', 'All meals during trekking days', 'Private transport'],
    excluded: ['Personal gear', 'Tips'],
    maxTravellers: 10,
    rating: 4.8,
    reviewCount: 22,
    destination: { name: 'Sonamarg', slug: 'sonamarg' },
  },
];

export const SEED_HOTELS: Listing[] = [
  {
    _id: 'seed-htl-1',
    name: 'The Royal Heritage Houseboat',
    slug: 'royal-heritage-houseboat',
    images: [{ url: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.8,
    pricePerNight: 4800,
    amenities: ['Dal Lake View', 'Central Heating', 'Free Wi-Fi', 'Wazwan Dining', '24/7 Shikara Shuttle'],
    destination: { name: 'Srinagar', slug: 'srinagar' },
  },
  {
    _id: 'seed-htl-2',
    name: 'The Khyber Himalayan Pine Resort',
    slug: 'the-khyber-resort',
    images: [{ url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.9,
    pricePerNight: 14500,
    amenities: ['Ski-in / Ski-out', 'Heated Indoor Pool', 'L’Occitane Spa', 'Mountain View', 'Luxury Lounge'],
    destination: { name: 'Gulmarg', slug: 'gulmarg' },
  },
  {
    _id: 'seed-htl-3',
    name: 'Pahalgam Riverside Pine Retreat',
    slug: 'pahalgam-riverside-retreat',
    images: [{ url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.7,
    pricePerNight: 5500,
    amenities: ['Lidder River Balcony', 'Outdoor Bonfire', 'Kashmiri Cuisine', 'Room Heating', 'Garden Lawn'],
    destination: { name: 'Pahalgam', slug: 'pahalgam' },
  },
  {
    _id: 'seed-htl-4',
    name: 'Sonamarg Alpine Glacier Lodge',
    slug: 'sonamarg-glacier-lodge',
    images: [{ url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.6,
    pricePerNight: 4200,
    amenities: ['Thajiwas Glacier View', 'Hot Water 24/7', 'Restaurant', 'Trek Gear Storage', 'Parking'],
    destination: { name: 'Sonamarg', slug: 'sonamarg' },
  },
];

export const SEED_VEHICLES: Vehicle[] = [
  { _id: 'seed-veh-1', category: 'sedan', name: 'Maruti Suzuki Dzire (Heated)', seats: 4, pricePerKm: 14, baseFare: 2800 },
  { _id: 'seed-veh-2', category: 'suv', name: 'Toyota Innova Crysta (4WD Available)', seats: 6, pricePerKm: 20, baseFare: 4200 },
  { _id: 'seed-veh-3', category: 'tempo_traveller', name: 'Luxury Tempo Traveller 12-Seater', seats: 12, pricePerKm: 32, baseFare: 7500 },
  { _id: 'seed-veh-4', category: 'suv', name: 'Mahindra Thar 4x4 Mountain Cab', seats: 4, pricePerKm: 24, baseFare: 4800 },
];

export const SEED_ACTIVITIES: Listing[] = [
  {
    _id: 'seed-act-1',
    name: 'Gulmarg Gondola Cable Car Ride (Phase 1 & 2)',
    slug: 'gulmarg-gondola-ride',
    images: [{ url: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.9,
    price: 1850,
    durationHours: 3,
    amenities: ['Skip-the-line coordination', 'Panoramic Apharwat Views', 'Snow photography points'],
    destination: { name: 'Gulmarg', slug: 'gulmarg' },
  },
  {
    _id: 'seed-act-2',
    name: 'Sunrise Shikara Ride & Floating Vegetable Market',
    slug: 'dal-lake-shikara-ride',
    images: [{ url: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.8,
    price: 850,
    durationHours: 2,
    amenities: ['Cushioned velvet seating', 'Kehwa tea onboard', 'Floating handicraft stops'],
    destination: { name: 'Srinagar', slug: 'srinagar' },
  },
  {
    _id: 'seed-act-3',
    name: 'Pahalgam White Water Rafting & Lidder Valley Walk',
    slug: 'pahalgam-river-rafting',
    images: [{ url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.7,
    price: 1400,
    durationHours: 2,
    amenities: ['Life jackets & safety gear', 'Grade II & III rapids', 'Certified river instructors'],
    destination: { name: 'Pahalgam', slug: 'pahalgam' },
  },
  {
    _id: 'seed-act-4',
    name: 'Thajiwas Glacier Pony & Snow Sledge Experience',
    slug: 'thajiwas-glacier-sledge',
    images: [{ url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80' }],
    rating: 4.6,
    price: 1100,
    durationHours: 3,
    amenities: ['Experienced local pony rider', 'Glacier crossing', 'Snow gumboot rental'],
    destination: { name: 'Sonamarg', slug: 'sonamarg' },
  },
];

export const SEED_BLOGS: Blog[] = [
  {
    _id: 'seed-blog-1',
    title: 'Best Time to Visit Kashmir: Month-by-Month Guide',
    slug: 'best-time-to-visit-kashmir',
    category: 'Travel Guides',
    tags: ['kashmir', 'seasons', 'tulip festival', 'snow'],
    excerpt: 'Spring blossoms, summer meadows, golden autumn chinars or winter snow: choose the exact season for your dream Himalayan journey.',
    content: [
      'Kashmir transforms with astonishing beauty across four distinct seasons. In April, the Asia’s largest Tulip Garden in Srinagar bursts into vibrant rainbow hues against the Zabarwan range.',
      'From May through August, lush green meadows carpet Gulmarg, Sonamarg, and Pahalgam, providing cool alpine breezes away from the summer plains.',
      'October brings the romantic Golden Autumn (Harud), when Chinar tree leaves turn fiery shades of crimson, saffron, and gold.',
      'From December to early March, Gulmarg and Sonamarg become snow-draped sanctuaries for skiing, snowboarding, and fairytale winter walks.',
    ],
    author: 'Wayfarer Editorial Team',
    createdAt: '2026-01-15T10:00:00.000Z',
  },
  {
    _id: 'seed-blog-2',
    title: 'Gulmarg Gondola Guide: Tickets, Phases & Tips',
    slug: 'gulmarg-travel-guide',
    category: 'Adventure',
    tags: ['gulmarg', 'gondola', 'skiing', 'tips'],
    excerpt: 'Everything you must know before booking the world’s second-highest cable car: ticket windows, phase 1 vs 2, weather precautions, and gear.',
    content: [
      'The Gulmarg Gondola rises from 2,600m to an exhilarating 3,950m at Apharwat Peak, bordering the Pir Panjal range.',
      'Phase 1 takes you from Gulmarg resort to Kongdoori station (3,050m), an easy, scenic ride suitable for children and seniors alike.',
      'Phase 2 ascends through alpine crags to Apharwat Ridge, where snow remains even in mid-summer. Always pack thermal layers, gloves, and UV sunglasses.',
      'Book official slots at least 2–3 weeks in advance during peak ski and summer holidays to avoid long queues.',
    ],
    author: 'Tariq Ahmad (Senior Mountain Guide)',
    createdAt: '2026-02-01T12:00:00.000Z',
  },
  {
    _id: 'seed-blog-3',
    title: 'Romantic Kashmir Honeymoon: The Ultimate 6-Day Flow',
    slug: 'kashmir-honeymoon-guide',
    category: 'Honeymoon',
    tags: ['honeymoon', 'houseboat', 'romantic', 'luxury'],
    excerpt: 'A carefully curated itinerary balancing vintage wooden houseboats on Dal Lake with secluded mountain pine cabins in Pahalgam.',
    content: [
      'Begin your journey with two romantic evenings aboard a carved cedarwood houseboat on Nigeen or Dal Lake.',
      'Take a private sunset shikara ride, sipping freshly brewed saffron kehwa while floating past lotus ponds and water-lily blossoms.',
      'Head south to Pahalgam, checking into a riverside retreat where private balconies look out over pine-covered hills and clear mountain streams.',
      'End your honeymoon above the clouds in Gulmarg with fireside dining and sweeping vistas of the snow-clad peaks.',
    ],
    author: 'Farhana Lone',
    createdAt: '2026-02-14T09:00:00.000Z',
  },
];
